// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackOverflowClone.Data;

#nullable disable

namespace StackOverflowClone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("StackOverflowClone.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "ASP.NET Core is a cross-platform web framework.",
                            PostedBy = "Charlie",
                            PostedDate = new DateTime(2025, 11, 11, 16, 49, 4, 547, DateTimeKind.Local).AddTicks(3631),
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "EF Core maps C# classes to database tables.",
                            PostedBy = "Dave",
                            PostedDate = new DateTime(2025, 11, 11, 16, 49, 4, 547, DateTimeKind.Local).AddTicks(3633),
                            QuestionId = 2
                        });
                });

            modelBuilder.Entity("StackOverflowClone.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Can someone explain the basics of ASP.NET Core?",
                            PostedBy = "Alice",
                            PostedDate = new DateTime(2025, 11, 11, 16, 49, 4, 547, DateTimeKind.Local).AddTicks(3545),
                            Title = "What is ASP.NET Core?"
                        },
                        new
                        {
                            Id = 2,
                            Body = "I want to understand EF Core with SQLite.",
                            PostedBy = "Bob",
                            PostedDate = new DateTime(2025, 11, 11, 16, 49, 4, 547, DateTimeKind.Local).AddTicks(3547),
                            Title = "How does EF Core work?"
                        });
                });

            modelBuilder.Entity("StackOverflowClone.Models.Answer", b =>
                {
                    b.HasOne("StackOverflowClone.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StackOverflowClone.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
